config/routes.rb
Rails.application.routes.draw do
  # обернем все доступные маршруты в скоп метод(объектом класса проц) для возможности переключения между локализациями
  # каждый наш маршрут теперь будет по умолчанию содержать локаль. 
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    # мы указали, чтобы стартовой страницей в корневой директории выводился через контролер posts и экшен который будет вызываться по умолчанию: index
    root 'posts#index'
    
    # команда создает за нас несколько маршрутов для нашего контролера
    resources :posts, only: [:show, :index]

    # создадим маршрут для контроллера tags для вывода тегов для экшена show 
    resources :tags, only: [:show]

    resources :categories, only: [:show] # для всех пользователей кроме админа ограничели маршруты только экшеном show 

    # создаем пространство имен и сюда нам нужно поместить те маршруты которые мы хотим для администратора в его админ панели.
    namespace :admin do
      resources :categories, except: [:show] # указали маршрут к контролерру categories и его экшенам(методам) кроме экшена show
      resources :posts, except: [:show, :index]
      # создаем маршруты для контролера, но так как у нас только два метода(экшена) создадим только для них маршруты
      resources :pictures, only: [:create, :destroy]
    end
  end
end

#Все это на DSL 

app/models/post.rb
class Post < ApplicationRecord
  #добавили возможность загружать изображение
  mount_uploader :image, ImageUploader

  belongs_to :category

  # создаем связи между моделями многие ко многим (связи в бд) через третью таблицу в БД taggings
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, :summary, :body, presence: true

  # метод на получение всех тегов геттер
  def all_tags
  	tags.map(&:name).join(', ')
  end

  # метод сеттер ищет или создает тек если нет такого
  def all_tags=(names)
  	self.tags = names.split(',').map do |name| # возможно из-за того, что вызвали блок и нужно указать напрямую self
  	  Tag.where(name: name.strip).first_or_create!
  	end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  # будет перед каждым экшином(методом) вызывать метод set_post, и ограничим за одно, чтобы вызывался только перед перечисленными методами
  before_action :set_post, only: %i[edit update destroy] # технически он вызовет указанный метод в нутри экшена, реализация либо добавив туда при интерпритации кода, либо просто сначала вызовет просто этот метод перед экшенами и только затем метод-экшен запустит.

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save # если сохранение валидно, успешно то
      redirect_to @post, success: 'Статья успешно создана' # направляем на отображение объекта
    else # во всех остальных случаях
      flash.now[:danger] = 'Статья не создана'
      render :new # направить и отобразить форму new
    end
  end

  def edit; end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Статья успешно обновлена'
    else
      flash.now[:danger] = 'Статья не обновлена'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Статья удалена' # направим на вывод всех статей после удаления
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  # приватный метод передающийся в аргументом в другой метод для фильтрации вводимых данных на уровне контроллера
  def post_params
    # означает, что в параметрах должен присутствовать только пост которому разрешаем только следующие поля totle, summary, body
    params.require(:post).permit(:title, :summary, :body, :image, :all_tags, :category_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # # Устанавливаем на все экшены кроме index и show контролера Posts накладывается ограничение пока пользователь не будет зарегестрирован, но оставим незарегистрированным спостреть данные вывадимые через методы index и show -> через вьюхи направит
  # before_action :authenticate_user!, except: %i[index show] # метод класса добавляющий специальный метод экземпляра (возможно приватный) имеющийся в геме devise который умолчанию вызывается во всех экшенах 

  # будет перед каждым экшином(методом) вызывать метод set_post, и ограничим за одно, чтобы вызывался только перед перечисленными методами
  before_action :set_post, only: :show # технически он вызовет указанный метод в нутри экшена, реализация либо добавив туда при интерпритации кода, либо просто сначала вызовет просто этот метод перед экшенами и только затем метод-экшен запустит.

  def index
    # с помощью gem "will_paginate", укажем сколько постов отображать на странице
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/posts/_delimeter.html.erb
<div class="page_delimeter">Страница <%= params[:page] %></div>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

	/**
	*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
	*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
	/*
	var disqus_config = function () {
	this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	};
	*/
	<%# на продакшене заменить на '<1%= request.base.url + request.original_fullpath %2>'; и сгенерируется автоматически домен%>
	var disqus_config = function () {
		this.page.url = 'http://localhost.com<%= request.original_fullpath %>';
		this.page.identifier = '<%= @post.id %>';
	};

	(function() { // DON'T EDIT BELOW THIS LINE
		var d = document, s = d.createElement('script');
		s.src = 'https://blog-v3.disqus.com/embed.js';
		s.setAttribute('data-timestamp', +new Date());
		(d.head || d.body).appendChild(s);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<!-- Выводим ошибку при попытки заполнения когда данные не валидны на уровне браузера -->
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor' %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form_control' %>
  </div>

  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: 'form_control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
     <!-- итерацию @posts.each не нужно указывать Рельсы самми сделают -->
     <h2><%= link_to post.title, post_path(post)%></h2>

     <small>
       <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
       <% if post.category.present? %>
         |
         <%= link_to post.category.name, post.category %>
       <% end %>
       
       <% if user_signed_in? && current_user.admin? %>
         |
         <%= link_to 'Изменить', edit_admin_post_path(post) %>
         |
         <%= link_to 'Удалить', admin_post_path(post), method: :delete, data: { confirm: 'Вы уверены?' } %>
       <% end %>
     </small>
  </section>

  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>

  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'badge badge-primary' }.join(' ') %>
  </section>
</article>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Новая статья', new_admin_post_path, class: 'btn btn-outline-primary btn-sm' %>
<% end %>

<!-- # будет использовать код итирации из _post.html.erb удобство в том, что нам не нужно там указывать цикл -->
<!-- обернем вывод наших статей в дополнительную секцию -->
<section id ='posts'>
	<%= render @posts %>
</section>

<!-- render page links in the view: также дополнительно подключим класс из initialis/bootstrap_pagination_helper.rb -->
<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/posts/index.js.erb
$('#posts').append("<%= j render(partial: 'delimeter') %>");
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
    $('.pagination').replaceWith("<%= j  will_paginate(@posts, renderer: 'BootstrapPaginationHelper::LinkRenderer') %>");
<% else %>
    $('.pagination').remove();
<% end %>

app/views/posts/show.html.erb
<%= render 'shared/breadcrumb', category: @post.category %>

<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if @post.category.present? %>
        |
        <%= link_to @post.category.name, @post.category %>
      <% end %>
      
      <% if user_signed_in? && current_user.admin? %>
        |
        <%= link_to 'Изменить', edit_admin_post_path(@post) %>
        |
        <%= link_to 'Удалить', admin_post_path(@post), method: :delete, data: { confirm: 'Вы уверены?' } %>
      <% end %>
    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <p><%= @post.body.html_safe %></p>
  </section>
</article>

<%= render 'disqus' %>