config/routes.rb
Rails.application.routes.draw do
  # обернем все доступные маршруты в скоп метод(объектом класса проц) для возможности переключения между локализациями
  # каждый наш маршрут теперь будет по умолчанию содержать локаль. 
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    # мы указали, чтобы стартовой страницей в корневой директории выводился через контролер posts и экшен который будет вызываться по умолчанию: index
    root 'posts#index'
    
    # команда создает за нас несколько маршрутов для нашего контролера
    resources :posts, only: [:show, :index]

    # создадим маршрут для контроллера tags для вывода тегов для экшена show 
    resources :tags, only: [:show]

    resources :categories, only: [:show] # для всех пользователей кроме админа ограничели маршруты только экшеном show 

    # создаем пространство имен и сюда нам нужно поместить те маршруты которые мы хотим для администратора в его админ панели.
    namespace :admin do
      resources :categories, except: [:show] # указали маршрут к контролерру categories и его экшенам(методам) кроме экшена show
      resources :posts, except: [:show, :index]
      # создаем маршруты для контролера, но так как у нас только два метода(экшена) создадим только для них маршруты
      resources :pictures, only: [:create, :destroy]
    end
  end
end

#Все это на DSL 

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true

  has_ancestry
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  # закроем для всех незарегестрированых пользователей (ограничения на все экшены)
  before_action :authenticate_user! # метод класса добавляющий специальный метод экземпляра (возможно приватный) имеющийся в геме devise который умолчанию вызывается во всех экшенах 

  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категория успешно создана'
    else
      flash[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категория успешно обновлена'
    else
      flash[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, success: 'Категория успешно удалена'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
  	@posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<!-- Выводим ошибку при попытки заполнения когда данные не валидны на уровне браузера -->
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :parent_id %>
    <%=  f.collection_select :parent_id, Category.where("id != ?", @category.id).order(:name), :id, :name, { include_blank: true }, class: 'form_control' %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @category.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div class="buttons_penel">
	<%= link_to 'Новая категория', new_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Название</th>
        <th>Категория родитель</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each.with_index(1) do |category, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= category.name %></td>
          <td><%= category.parent.name if category.parent.present? %></td>
          <td>
            <%= link_to 'Изменить', edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
            <%= link_to 'Удалить', category_path(category), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-outline-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/categories/show.html.erb
<%= render 'shared/breadcrumb', category: @category %>

<h1><%= @category.name %></h1>

<section id='posts'>
	<%= render @posts %>
</section>

<!-- render page links in the view: также дополнительно подключим класс из initialis/bootstrap_pagination_helper.rb -->
<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/categories/show.js.erb
$('#posts').append("<%= j render(partial: 'posts/delimeter') %>");
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
    $('.pagination').replaceWith("<%= j  will_paginate(@posts, renderer: 'BootstrapPaginationHelper::LinkRenderer') %>");
<% else %>
    $('.pagination').remove();
<% end %>