config/routes.rb
Rails.application.routes.draw do
  # обернем все доступные маршруты в скоп метод(объектом класса проц) для возможности переключения между локализациями
  # каждый наш маршрут теперь будет по умолчанию содержать локаль. 
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    # мы указали, чтобы стартовой страницей в корневой директории выводился через контролер posts и экшен который будет вызываться по умолчанию: index
    root 'posts#index'
    
    # команда создает за нас несколько маршрутов для нашего контролера
    resources :posts, only: [:show, :index]

    # создадим маршрут для контроллера tags для вывода тегов для экшена show 
    resources :tags, only: [:show]

    resources :categories, only: [:show] # для всех пользователей кроме админа ограничели маршруты только экшеном show 

    # создаем пространство имен и сюда нам нужно поместить те маршруты которые мы хотим для администратора в его админ панели.
    namespace :admin do
      resources :categories, except: [:show] # указали маршрут к контролерру categories и его экшенам(методам) кроме экшена show
      resources :posts, except: [:show, :index]
      # создаем маршруты для контролера, но так как у нас только два метода(экшена) создадим только для них маршруты
      resources :pictures, only: [:create, :destroy]
    end
  end
end

#Все это на DSL 

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogV3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          <%= 'Теги:' %>
            <!-- используем созданный нами хелпер tag_cloud -->
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: 'badge badge-primary' %>
            <% end %>
        </button>

        <a class="navbar-brand" href="#"><%= link_to 'Новая статья', new_admin_post_path, class: 'btn btn-outline-primary pull-xs-right' %></a>

        <ul class="nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <!-- это просто разные способы создания ссылок: -->
              <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_registration_path %>">Регистрация<span class="sr-only">(current)</span></a>
            </li>
          <% end %>
          <li class="nav-item<%= " active" if I18n.locale == :ru %>">
              <%= link_to "Рус", { locale: :ru }, class: "nav-link" %>
            </li>
            <li class="nav-item<%= " active" if I18n.locale == :en %>">
              <%= link_to "En", { locale: :en }, class: "nav-link" %>
          </li>
        </ul>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav navbar-nav">
            <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
              <a class="nav-link" href="<%= root_path %>">Все статьи<span class="sr-only">(current)</span></a>
            </li>
            <% Category.order(:name).roots.each do |category| %>
              <li class="nav-item <%= 'active' if current_page?(category_path(category)) %>"><%= link_to category.name, category, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>    
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= yield %>
        </div>

        <div class="col-md-3">
          <%= render 'shared/submenu' %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogV3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          <%= 'Теги:' %>
            <!-- используем созданный нами хелпер tag_cloud -->
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: 'badge badge-primary' %>
            <% end %>
        </button>

        <a class="navbar-brand" href="#"><%= link_to 'Новая статья', new_admin_post_path, class: 'btn btn-outline-primary pull-xs-right' %></a>

        <ul class="nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <!-- это просто разные способы создания ссылок: -->
              <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_registration_path %>">Регистрация<span class="sr-only">(current)</span></a>
            </li>
          <% end %>
          <li class="nav-item<%= " active" if I18n.locale == :ru %>">
              <%= link_to "Рус", { locale: :ru }, class: "nav-link" %>
            </li>
            <li class="nav-item<%= " active" if I18n.locale == :en %>">
              <%= link_to "En", { locale: :en }, class: "nav-link" %>
          </li>
        </ul>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav navbar-nav">
            <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
              <a class="nav-link" href="<%= root_path %>">Все статьи<span class="sr-only">(current)</span></a>
            </li>
            <% Category.order(:name).roots.each do |category| %>
              <li class="nav-item <%= 'active' if current_page?(category_path(category)) %>"><%= link_to category.name, category, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>    
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= yield %>
        </div>

        <div class="col-md-3">
          <%= render 'shared/submenu' %>
        </div>
      </div>
    </div>
  </body>
</html>